name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "apps/frontend/**"
  pull_request:
    branches:
      - main
    paths:
      - "apps/frontend/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/frontend
    concurrency:
      group: frontend-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: apps/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --progress=false

      - name: Build application
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: apps/frontend/dist

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend-build

      - name: Deploy to production
        uses: azure/webapps-deploy@v2
        with:
          package: ./frontend-build
          app-name: ${{ secrets.FRONTEND_AZURE_APPSERVICE_NAME }}
          publish-profile: ${{ secrets.FRONTEND_AZURE_PUBLISH_PROFILE }}
