name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "apps/frontend/**"
  pull_request:
    branches:
      - main
    paths:
      - "apps/frontend/**"
  workflow_dispatch:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: apps/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Upload built dist
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: apps/frontend/dist

  deploy:
    name: Deploy to Azure
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore built dist artifact into apps/frontend/dist
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: apps/frontend/dist

      - name: Deploy to Azure Static Web App (upload existing artifact)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_MUD_00194F203 }}
          action: "upload"
          app_location: "apps/frontend" # repo-root-relative path to your app
          api_location: "" # empty if no Azure Functions API
          output_location: "dist" # folder inside app_location containing build
          skip_app_build: true # we already built and uploaded the artifact
