name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "apps/frontend/**"
  pull_request:
    branches:
      - main
    paths:
      - "apps/frontend/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install
        working-directory: apps/frontend

      - name: Build application
        run: npm run build
        working-directory: apps/frontend

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install
        working-directory: apps/frontend

      - name: Build application
        run: npm run build
        working-directory: apps/frontend

      - name: Deploy to production
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.FRONTEND_AZURE_APPSERVICE_NAME }}
          publish-profile: ${{ secrets.FRONTEND_AZURE_PUBISH_PROFILE }}
